server {
    listen 0.0.0.0:8089;
    server_name _;
    root /www/wwwroot/wafpanel;
    index index.html index.php;
    charset utf-8;
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires -1;
    }
    location ~ \.php$ {
        fastcgi_pass unix:/tmp/php-cgi-82.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
